src/Entity/Property.php
<?php

namespace App\Entity;

use App\Repository\PropertyRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=PropertyRepository::class)
 * @UniqueEntity("title")
 * @Vich\Uploadable()
 */
class Property
{
    const Heat=[
        0=>'Electric',
        1=>'Gaz'
    ];


    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string
     * @ORM\Column(type="string", length=255)
     */
    private $filename;

    /**
     * @var File|null
     * @Assert\Image(mimeTypes="image/jpeg")
     * @Vich\UploadableField(mapping="property", fileNameProperty="filename")
     */
    private $imageFile;


    /**
     * @Assert\Length(min=5,max=50)
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(min=10,max=500)
     */
    private $surface;

    public function getFormattedPrice(): string
        {
            return number_format($this->price,0,'',' ');
        }
    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $bedrooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $floors;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     */
    private $heat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adress;

    /**
     * @Assert\Regex("/^[0-9]{5}$/")
     * @ORM\Column(type="string", length=255)
     */
    private $postal_code;

    /**
     * @ORM\Column(type="boolean",options={"default": false})
     */
    private $sold;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\ManyToMany(targetEntity=Option::class, inversedBy="properties")
     */
    private $options;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    /**
     * @ORM\Column(type="integer")
     *
     * @var int|null
     */
    private $imageSize;

    public function __construct()
    {
        $this->created_at=new \DateTime();
        $this->sold=false;
        $this->options = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }
    public function getHeatType(): string
    {
        return self::Heat[$this->heat];
    }

    public function getSlug(): string
    {
        return (new Slugify())->slugify('Hello');

    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getFloors(): ?int
    {
        return $this->floors;
    }

    public function setFloors(int $floors): self
    {
        $this->floors = $floors;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getHeat(): ?int
    {
        return $this->heat;
    }

    public function setHeat(int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(string $adress): self
    {
        $this->adress = $adress;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }



    /**
     * @param mixed $id
     */
    public function setId($id): void
    {
        $this->id = $id;
    }

    /**
     * @return Collection<int, Option>
     */
    public function getOptions(): Collection
    {
        return $this->options;
    }

    public function addOption(Option $option): self
    {
        if (!$this->options->contains($option)) {
            $this->options[] = $option;
            $option->addProperty($this);
        }

        return $this;
    }

    public function removeOption(Option $option): self
    {
        if ($this->options->removeElement($option)) {
            $option->removeProperty($this);
        }

        return $this;
    }

    /**
     * @return File
     */
    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    /**
     * @param File $imageFile
     * @return Property
     */
    public function setImageFile(File $imageFile): Property
    {
        $this->imageFile=$imageFile;

        if($this->imageFile instanceof UploadedFile)
        {
            $this->updated_at=new \DateTime('now');
        }

        return $this;
    }

    /**
     * @return string|null
     */
    public function getFilename(): ?string
    {
        return $this->filename;
    }

    /**
     * @param string|null $filename
     * @return Property
     */
    public function setFilename(string $filename=null): Property
    {
        $this->filename = $filename;
        return $this;
    }

    public function getUpdatedAt(): ?\DateTime
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTime $updated_at): self
    {
        $this->updated_at = $updated_at;
        return $this;
    }

    /**
     * @return int|null
     */
    public function getImageSize(): ?int
    {
        return $this->imageSize;
    }

    /**
     * @param int|null $imageSize
     * @return Property
     */
    public function setImageSize(?int $imageSize): Property
    {
        $this->imageSize = $imageSize;
        return $this;
    }


}

src/Form/PropertyType.php
<?php

namespace App\Form;

use App\Entity\Option;
use App\Entity\Property;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Vich\UploaderBundle\Form\Type\VichFileType;
use Vich\UploaderBundle\Form\Type\VichImageType;

class PropertyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('surface')
            ->add('rooms')
            ->add('bedrooms')
            ->add('floors')
            ->add('price')
            ->add('heat',ChoiceType::class,[
                'choices'=>$this->getChoices()
            ])
            ->add('options',EntityType::class,[
                'class'=>Option::class,
                'choice_label'=>'name',
                'multiple'=>true
            ])
            ->add('imageFile',FileType::class,[
                'required'=>false,
                'empty_data' => ''
            ])
            ->add('city')
            ->add('adress')
            ->add('postal_code')
            ->add('sold')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Property::class,
            'translation_domain'=>'forms',
        ]);
    }
    public function getChoices(): array
    {
        $choices=Property::Heat;
        $output = [];
        foreach ($choices as $k=>$v)
        {
            $output[$v]=$k;
        }
        return $output;
    }
}

src/Controller/PropertyController.php
<?php

namespace App\Controller;

use App\Entity\Contact;
use App\Entity\Property;
use App\Entity\PropertySearch;
use App\Form\ContactType;
use App\Form\PropertySearchType;
use App\Notification\ContactNotification;
use App\Repository\PropertyRepository;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ObjectManager;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class PropertyController extends AbstractController
{
    /**
     * @var PropertyRepository
     */
    private $repository;
    /**
     * @var EntityManagerInterface
     */
    private $em;

    public function __construct(PropertyRepository $repository,EntityManagerInterface $em)
    {
        $this->repository=$repository;   
        $this->em=$em;
    }

    /**
     * @Route("/store",name="product.index")
     */
    public function index(PaginatorInterface $paginator, Request $request):Response
    {
        $search = new PropertySearch();
        $form = $this->createForm(PropertySearchType::class,$search);
        $form->handleRequest($request);

        $property =$paginator->paginate($this->repository->findAllVisibleQuery($search),
            $request->query->getInt('page', 1),
            12
        );

        return $this->render('property/index.html.twig',[
            'current_menu'=>'property',
            'property'=>$property,
            'form'=>$form->createView()
        ]);
    }

    /**
     * @Route("/store/{slug}-{id}", name="property.show", requirements={"slug":"[a-z0-9\-]*"})
     */
    public function show(Property $property,string $slug,Request $request,ContactNotification $contactNotification):Response
    {
        if($property->getSlug()!==$slug)
        {
            return $this->redirectToRoute('property.show',[
                'id'=>$property->getId(),
                'slug'=>$property->getSlug()
            ],301);
        }
        $contact = new Contact();
        $contact->setProperty($property);
        $form=$this->createForm(ContactType::class,$contact);
        $form->handleRequest($request);

        if($form->isSubmitted()&&$form->isValid())
        {
            $contactNotification->notify($contact);
            $this->addFlash('success','EMAILED SUCCESSFULLY!');
            /*return $this->redirectToRoute('property.show',[
               'id'=>$property->getId(),
               'slug'=>$property->getSlug()
            ]);*/
        }

        return $this->render('property/show.html.twig',[
            'property'=>$property,
            'current_menu'=>'property',
            'form'=>$form->createView()
        ]);

    }

}

templates/property/_property.html.twig
<div class="card mb-2">

    <div class="card-body">
        <h5 class="card-title">
            {% if prop.filename %}
                <img src="{{ vich_uploader_asset(prop, 'imageFile')|imagine_filter('thumb') }}" alt="card-img-top" width=100%>
            {% endif %}
            <a href="{{ path('property.show', {slug: prop.slug, id:prop.id}) }}">
                {{ prop.title }}
            </a>
        </h5>
        <p class="card-text">{{ prop.surface }}m² {{ prop.city }} {{ prop.postalCode }}</p>
        <div class="text-primary" style="font-size: 2rem;font-weight: bold;">
            {{ prop.price|number_format(0,'',' ') }}$
        </div>

    </div>
</div>

templates/property/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Welcome!
{% endblock %}
{% block body %}
    <div class="container text-center" style="font-family: 'Bahnschrift',Serif,serif">
        <h1>OUR STORE</h1>
        <h5>Best Offers in The Market</h5>
    </div>
    <br>
    <div class="jumbotron" style="font-family: 'Bahnschrift',Serif,serif">
        <div class="container" style="width: 30%;margin-left:0 ">
            <h4>Do you want help?</h4>
            <span>SEARCH IN HERE!</span>
            {{ form_start(form) }}
            <div class="form-row align-items-end">
                <div class="col">
                    {{ form_row(form.minSurface)}}
                </div>
                <div class="col">
                    {{ form_row(form.maxPrice) }}
                </div>
                <div class="col">
                    {{ form_row(form.options) }}
                </div>
                <div class="col">
                    <button class="btn btn-primary">SEARCH</button>
                </div>
            </div>
            {{ form_end(form) }}
        </div>

    </div>
    <br>
    <div class="row">
        {% for prop in property %}
            <div class="col-md-4">{% include 'property/_property.html.twig' %}</div>
        {% endfor %}
    </div>
    <div class="pagination">
        {{ knp_pagination_render(property) }}
    </div>

{% endblock %}

templates/property/show.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container mt-4" style="margin-left: -380px;width: 100%">
        <div class="row">

            <div class="col-md-8">

            </div>

            <div class="col-md-4 text-center" style="background-color: #5eb5e0">
                {% for msg in app.flashes('success') %}
                    <div class="alert alert-success">
                        {{ msg }}
                    </div>
                {% endfor %}
                {% if not form.vars.valid %}
                    <div class="alert alert-danger">
                        Error
                    </div>
                {% endif %}
                <h1>{{ property.title }}</h1>
                <h2>{{ property.rooms }} Pieces -- {{ property.surface }}m²</h2>
                <div class="text-primary" style="font-size: 2rem;font-weight: bold">{{ property.formattedPrice }}$</div>
                <br><a href="#" class="btn btn-primary">Contact Agency</a>
                <div id="contactForm" class="mt-4">
                    {{ form_start(form) }}
                    <div class="row">
                        <div class="col">
                            {{ form_row(form.firstname) }}
                        </div>
                        <div class="col">
                            {{ form_row(form.lastname) }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            {{ form_row(form.phone) }}
                        </div>
                        <div class="col">
                            {{ form_row(form.email) }}
                        </div>
                    </div>
                    {{ form_rest(form) }}
                    <div class="form-group">
                        <button class="btn btn-primary">SEND</button>
                    </div>
                    {{ form_end(form) }}
                </div>
            </div>
        </div>

        <div>
            <h2 class="text-center" style="margin-right: 190px">Characteristics</h2><br>
            <table style="margin: -10px 10px 10px 450px" class="table table-striped">

                <tr>
                    <td>Surface Area</td>
                    <td>{{ property.surface }}m²</td>
                </tr>
                <tr>
                    <td>Pieces</td>
                    <td>{{ property.rooms }}</td>
                </tr>
                <tr>
                    <td>Bedrooms</td>
                    <td>{{ property.bedrooms }}</td>
                </tr>
                <tr>
                    <td>Floors</td>
                    <td>{{ property.floors }}</td>
                </tr>
                <tr>
                    <td>Air Conditioning</td>
                    <td>{{ property.heatType }}</td>
                </tr>
            </table>
        </div>
        <div class="col-md-4">
            <h4 class="text-center" style="margin-right: -600px;color: #dc3545">Specification</h4>
            <h5 class="text-center" style="margin-right: -620px;color: royalblue">{{ property.description|nl2br }}</h5><br>
        </div>
    </div>
{% endblock %}

{% block title %}
PRODUCTS
{% endblock %}